### ISSUE TITLE
Fix default postgresql connection string construction

### ISSUE THREAD

**Issue by marcwrobel** [marcwrobel/gcli#16]
Since gcli 0.0.4 executing a script with default arguments result in the following error :
```
Caught: java.sql.SQLException: No suitable driver found for false
java.sql.SQLException: No suitable driver found for false
	at fr.marcwrobel.gcli.DatabaseConfiguration.withSql(DatabaseConfiguration.groovy:30)
	at fr.marcwrobel.gcli.DatabaseConfiguration$withSql.call(Unknown Source)
	at ThetysKycAuthentications.execute(thetys-kyc-authentications:55)
	at ThetysKycAuthentications$execute.call(Unknown Source)
	at thetys-kyc-authentications.run(thetys-kyc-authentications:172)
```

**Comment by marcwrobel** [comment]
Adding some logs in `DatabaseConfiguration.withSql(...)` results in the following message : `Connecting to database using URL=false, user=mwrobel, driver=org.postgresql.Driver [DEBUG] `.

The error is in the `getDatabaseUrl()` method which does not properly check if `options.dc` is set or not.
